# Project: Edytor
# Makefile created by Dev-C++ 4.9.9.0

CPP  = g++.exe -D__DEBUG__
CC   = gcc.exe -D__DEBUG__
WINDRES = windres.exe
RES  = Edytor_private.res
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"C:/Programy/Programowanie/Dev-Cpp/lib" -mwindows C:/Programy/Programowanie/Dev-Cpp/lib/libcomctl32.a C:/Programy/Programowanie/Dev-Cpp/lib/libshlwapi.a  -g3 
INCS =  -I"C:/Programy/Programowanie/Dev-Cpp/include" 
CXXINCS =  -I"C:/Programy/Programowanie/Dev-Cpp/include/c++"  -I"C:/Programy/Programowanie/Dev-Cpp/include/c++/mingw32"  -I"C:/Programy/Programowanie/Dev-Cpp/include/c++/backward"  -I"C:/Programy/Programowanie/Dev-Cpp/include" 
BIN  = Edytor.exe
CXXFLAGS = $(CXXINCS)   -g3
CFLAGS = $(INCS)   -g3

.PHONY: all all-before all-after clean clean-custom

all: all-before Edytor.exe all-after


clean: clean-custom
	rm -f $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Edytor.exe" $(LIBS)

main.o: main.cpp C:/Programy/Programowanie/Dev-Cpp/include/windows.h   C:/Programy/Programowanie/Dev-Cpp/include/stdio.h   C:/Programy/Programowanie/Dev-Cpp/include/commctrl.h   C:/Programy/Programowanie/Dev-Cpp/include/Shlwapi.h kontrolki.h
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Edytor_private.res: Edytor_private.rc resource.rc 
	$(WINDRES) -i Edytor_private.rc -I rc -o Edytor_private.res -O coff 
